sectors:
    hn-fallback:
        - feedback
        - use
        - python
        - project
        - open-source
        - using
        - time
        - code
        - building
        - browser
        - make
        - language
        - data
        - get
        - would
        - see
        - also
        - love
        - built
        - software
        - people
        - programming
        - like
        - video
        - simple
