sectors:
    arxiv-fallback:
        - temperature
        - offers
        - dynamics
        - preserves
        - fine-tuning
        - data-driven
        - upper
        - non-linear
        - prevent
        - basis
        - healthcare
        - continuous
        - advancing
        - decoding
        - best
        - characterize
        - aggregation
        - due
        - framework
        - policy
        - collected
        - function
        - pretraining
        - mapping
        - activity
        - nonlinear
        - incorporate
        - enhancing
        - signal
        - analyzing
        - surrogate
        - practical
        - demand
        - presents
        - towards
        - equations
        - paradigms
        - spatial
        - predictions
        - strong
        - values
        - multivariate
        - development
        - identifies
        - operational
        - sample
        - employing
        - matrix
        - integration
        - size
        - two
        - forecasting
        - iterative
        - found
        - datasets
        - engineering
        - downstream
        - aligned
        - choice
        - established
        - consistently
        - risk
        - accuracy
        - multiple
        - enhanced
        - reliable
        - produces
        - retrieval
        - search
        - detection
        - theory
        - management
        - adaptation
        - threshold
        - feasibility
        - degradation
        - transformer
        - convergence
        - unit
        - speedup
        - reduced
        - analyze
        - multimodal
        - apply
        - rigorous
        - perform
        - mechanism
        - spaces
        - effective
        - resource
        - related
        - efficiency
        - interactions
        - action
        - updates
        - evidence
        - individual
        - direct
        - investigate
        - density
        - one
        - characterized
        - patients
        - energy
        - common
        - total
        - selecting
        - policies
        - universal
        - descent
        - confirm
        - adaptively
        - optimized
        - regimes
        - furthermore
        - techniques
        - errors
        - reasoning
        - bound
        - agentic
        - platforms
        - pre-trained
        - central
        - compromise
        - task-specific
        - five
        - open
        - language
        - around
        - planning
        - level
        - groups
        - trained
        - complementary
        - resource-constrained
        - numerical
        - medical
        - robustness
        - growth
        - designing
        - environments
        - inputs
        - suggest
        - compression
        - highlight
        - application
        - uniform
        - functions
        - estimated
        - decision-making
