sectors:
    hn-fallback:
        - using
        - get
        - python
        - make
        - use
        - like
        - video
        - see
        - love
        - would
        - browser
        - feedback
        - open-source
        - programming
        - built
        - code
        - language
        - project
        - building
        - simple
        - time
        - people
        - also
        - data
        - software
